spring:
        application:
          name: portfolio
        datasource:
          url: jdbc:postgresql://localhost:5433/portfolio
          username: franmb93
          password: franmb93
        jpa:
          hibernate:
            ddl-auto: update
          show-sql: true
          properties:
            hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect